logo: "/images/avatar.png?raw=true" # your photo (or logo) here
title: Christine Shrader # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>Entrepreneurial Spirit</b>
  <br><br>
  <b>Logical Thinker</b>
  <br><br>
  <b>Relentless Problem Solver</b>
  <hr>
  
  <a href="https://www.linkedin.com/in/christine-shrader-32044264/">View My LinkedIn Profile</a> 
  <br>
  <br>
  <img src="images/check.png?raw=true" style="width:10px;height:10px;"/>
  Right to work in the UK without sponsorship
  <br>
  <br>
  <br>
  
theme: jekyll-theme-minimal

