logo: "/images/avatar.png?raw=true" # your photo (or logo) here
title: Christine Shrader # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>Entrepreneurial Spirit</b>
  <br><br>
  <b>Logical Thinker</b>
  <br><br>
  <b>Relentless Problem Solver</b>
  <hr>
  
  <a href="https://www.linkedin.com/in/christine-shrader-32044264/">View My LinkedIn Profile</a> 
  <br>
icon: fa-check
  Right to work in the UK without sponsorship
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
